### ISSUE TITLE
Intermittent issues with BitBucket deploy

### ISSUE THREAD

**Issue by sgmeyer** [auth0-extensions/auth0-bitbucket-deploy#18]
When deploying from a BitBucket repository I receive the following error:

```
2017-05-03T08:37:52.155Z - Getting access token for randomness/tenant.eu.auth0.com
2017-05-03T08:37:53.509Z - Assets: {"rules":{"print-config":{"script":true,"metadata":true,"name":"print-config","scriptFile":"2ffb629dd2945fb89f87539b0df3ac3cbcc69764c905582cade9071b048a039a","metadataFile":"{\"enabled\":false,\"order\":100}"},"require-stuff":{"script":true,"metadata":true,"name":"require-stuff","metadataFile":"{\"enabled\":true,\"order\":10,\"stage\":\"login_success\"}","scriptFile":"6cb880292a470f15fb743fbf411fb0ebf7cb392e5b67f0158e3aa07237c0cdf0"}},"pages":{"login":{"metadata":true,"name":"login","metadataFile":"{\"enabled\":true}","htmlFile":"7b119f78faa3101c0bcd684ec307aa0bd9d9a72b3615f7fa8380f9926f265b24"},"password_reset":{"metadata":true,"name":"password_reset","htmlFile":"8f0b6646966aac7bb9c7f0ea0d7544fa077b3cb010aa2c30734dddfffc2c5c6b","metadataFile":"{\"enabled\":true}"}},"databases":[]}
2017-05-03T08:37:53.523Z - Updating pages...
2017-05-03T08:37:53.524Z - Updating login page...
2017-05-03T08:37:53.525Z - Error: Cannot read property 'clients' of undefined
2017-05-03T08:37:53.526Z - StackTrace: TypeError: Cannot read property 'clients' of undefined
   at Object.a.getGlobalClientId (/data/auth0-bitbucket-deploy-2.2.js:1:28841)
   at Object.a.updateLoginPage (/data/auth0-bitbucket-deploy-2.2.js:1:29926)
   at Object.a.updatePages (/data/auth0-bitbucket-deploy-2.2.js:1:30149)
   at /data/auth0-bitbucket-deploy-2.2.js:2:4427
   at tryCatcher (/data/_verquire/mongoose/4.1.6/node_modules/bluebird/js/main/util.js:24:31)
   at Promise._settlePromiseFromHandler (/data/_verquire/mongoose/4.1.6/node_modules/bluebird/js/main/promise.js:454:31)
   at Promise._settlePromiseAt (/data/_verquire/mongoose/4.1.6/node_modules/bluebird/js/main/promise.js:530:18)
   at Promise._settlePromises (/data/_verquire/mongoose/4.1.6/node_modules/bluebird/js/main/promise.js:646:14)
   at bound (domain.js:287:14)
   at Promise.runBound (domain.js:300:12)
   at Async._drainQueue (/data/_verquire/mongoose/4.1.6/node_modules/bluebird/js/main/async.js:182:12)
   at Async._drainQueues (/data/_verquire/mongoose/4.1.6/node_modules/bluebird/js/main/async.js:187:10)
   at Immediate.Async.drainQueues [as _onImmediate] (/data/_verquire/mongoose/4.1.6/node_modules/bluebird/js/main/async.js:15:14)
   at processImmediate [as _immediateCallback] (timers.js:383:17)
2017-05-03T08:37:53.526Z - Sending progress to Slack.
```

**Comment by zxan1285** [comment]
Fixed in #19
